set backupdir=~/.vim/bak/
set encoding=utf8
set bg=dark
set tabstop=4
set shiftwidth=4
set smartindent
set hlsearch
syntax on
set backspace=start,eol,indent

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'derekwyatt/vim-scala'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" Toggle paste mode for pasting from Clipboard.
set pastetoggle=<F2>

" Set soft word wrap.
set wrap linebreak nolist
map <Down> gj
map <Up> gk
" Mark tabs and spaces. TODO goes into conflict with soft word wrap
"set list listchars=tab:»\ ,trail:·,extends:»,precedes:«

" Load manual pages.
runtime ftplugin/man.vim

" Enable ftplugin for code style based in file type.
filetype plugin on

" Set tex flavor
let g:tex_flavor = 'latex'

" Pig / Hive
augroup filetypedetect
  au BufNewFile,BufRead *.pig set filetype=pig syntax=pig
  au BufNewFile,BufRead *.hql set filetype=sql
augroup END

" Tell vim to remember certain things when we exit
"  '10  :  marks will be remembered for up to 10 previously edited files
"  "100 :  will save up to 100 lines for each register
"  :20  :  up to 20 lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files
set viminfo='10,\"100,:20,%,n~/.viminfo

function! ResCur()
  if line("'\"") <= line("$")
    normal! g`"
    return 1
  endif
endfunction

augroup resCur
  autocmd!
  autocmd BufWinEnter * call ResCur()
augroup END
