set backupdir=~/.vim/bak/
set encoding=utf8

" Mark tabs and spaces.
set list listchars=tab:»\ ,trail:·,extends:»,precedes:«

" Load manual pages.
runtime ftplugin/man.vim

" Enable ftplugin for code style based in file type.
filetype plugin on

" Set tex flavor
let g:tex_flavor = 'latex'

" Tell vim to remember certain things when we exit
"  '10  :  marks will be remembered for up to 10 previously edited files
"  "100 :  will save up to 100 lines for each register
"  :20  :  up to 20 lines of command-line history will be remembered
"  %    :  saves and restores the buffer list
"  n... :  where to save the viminfo files
set viminfo='10,\"100,:20,%,n~/.viminfo
